dynaconf_merge: true
default:
  NAME: media_service
  HOST: 0.0.0.0
  PORT: 8003
  FAST_API_PATH: src.application:app
  LOG_LEVEL: info
  RELOADED: True
  POSTGRES:
    dialect: asyncpg
    host: postgres
    port: 5432
    login: postgres
    password: postgres
    database: postgres
    pgbouncer: False
    echo: False
    pool_min_size: 10
    pool_max_size: 20
    pool_timeout: 90
    mat_view_time: 15
  REDIS:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  KAFKA:
    routing_key: routing_key
    host: localhost
    port: 9092
    topics:
      - service_name.topic
  S3:
    protocol: http
    host: localhost
    port: 9000
    access_key:
    secret_key:
    region:
    chunk_size:
  S3_ERRORS:
    NO_SUCH_BUCKET: NoSuchBucket
    NO_SUCH_FILE: NoSuchKey
    MINIO_STORAGE_FULL: XMinioStorageFull
