"""create model

Revision ID: ca3454216f5e
Revises: 
Create Date: 2024-09-29 10:56:46.049557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca3454216f5e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("name", sa.Text(), nullable=False, comment="Название"),
        sa.Column("references", sa.Text(), nullable=True, comment="Связанный объект"),
        sa.Column(
            "reference_uuid",
            sa.UUID(),
            nullable=True,
            comment="Идентификатор связанного объекта",
        ),
        sa.Column("bucket", sa.Text(), nullable=False, comment="Bucket хранилища"),
        sa.Column("path", sa.Text(), nullable=False, comment="Путь к файлу в bucket"),
        sa.Column(
            "mimetype",
            sa.Text(),
            nullable=False,
            comment="Тип файла по спецификации MIME",
        ),
        sa.Column(
            "jdata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
            comment="Доп данные",
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
            comment="Теги",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_files_reference_uuid"),
        "files",
        ["reference_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_files_references"), "files", ["references"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_references"), table_name="files")
    op.drop_index(op.f("ix_files_reference_uuid"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
